# Seed data exported from current database
TodoListItem.unscoped.delete_all
TodoList.delete_all

supermercado_del_mes = TodoList.create!(name: "Supermercado del mes")
[
  ["Leche entera (1L)", nil, true],
  ["Leche descremada (1L)", nil, true],
  ["Yogur natural", nil, true],
  ["Yogur griego", nil, true],
  ["Queso mozzarella", nil, true],
  ["Queso cheddar", nil, true],
  ["Queso brie", nil, true],
  ["Queso parmesano", nil, true],
  ["Manteca sin sal", nil, true],
  ["Crema de leche", nil, true],
  ["Huevos (docena)", nil, true],
  ["Claras de huevo", nil, true],
  ["Pan de campo", nil, true],
  ["Pan integral", nil, true],
  ["Pan de molde", nil, true],
  ["Medialunas", nil, true],
  ["Manzanas Granny Smith", nil, true],
  ["Manzanas Red Delicious", nil, true],
  ["Peras Williams", nil, true],
  ["Duraznos", nil, true],
  ["Bananas", nil, false],
  ["Naranjas", nil, false],
  ["Mandarinas", nil, false],
  ["Limones", nil, false],
  ["Pomelos", nil, false],
  ["Uvas verdes", nil, false],
  ["Uvas negras", nil, false],
  ["Frutillas", nil, false],
  ["Frambuesas", nil, false],
  ["Arándanos", nil, false],
  ["Kiwi", nil, false],
  ["Melón", nil, false],
  ["Sandía", nil, false],
  ["Mango", nil, false],
  ["Piña", nil, false],
  ["Ananá en lata", nil, false],
  ["Dátiles", nil, false],
  ["Tomates cherry", nil, false],
  ["Tomates perita", nil, false],
  ["Tomates redondos", nil, false],
  ["Lechuga mantecosa", nil, false],
  ["Lechuga iceberg", nil, false],
  ["Rúcula", nil, false],
  ["Espinaca", nil, false],
  ["Zanahoria", nil, false],
  ["Zucchini", nil, false],
  ["Berenjena", nil, false],
  ["Pimiento rojo", nil, false],
  ["Pimiento verde", nil, false],
  ["Pimiento amarillo", nil, false],
  ["Brócoli", nil, false],
  ["Coliflor", nil, false],
  ["Repollo blanco", nil, false],
  ["Repollo morado", nil, false],
  ["Cebolla blanca", nil, false],
  ["Cebolla morada", nil, false],
  ["Cebolla de verdeo", nil, false],
  ["Ajo", nil, false],
  ["Jengibre", nil, false],
  ["Apio", nil, false],
  ["Puerro", nil, false],
  ["Remolacha", nil, false],
  ["Choclo", nil, false],
  ["Arvejas frescas", nil, false],
  ["Chaucha", nil, false],
  ["Papas", nil, false],
  ["Papas andinas", nil, false],
  ["Batata", nil, false],
  ["Mandioca", nil, false],
  ["Pechuga de pollo", nil, false],
  ["Muslo de pollo", nil, false],
  ["Pollo entero", nil, false],
  ["Hamburguesas de pollo", nil, false],
  ["Carne picada", nil, false],
  ["Bife de chorizo", nil, false],
  ["Asado", nil, false],
  ["Costillas", nil, false],
  ["Vacío", nil, false],
  ["Lomo", nil, false],
  ["Milanesas de ternera", nil, false],
  ["Salchicha parrillera", nil, false],
  ["Salmon", nil, false],
  ["Merluza filetes", nil, false],
  ["Atún en lata", nil, false],
  ["Sardinas en lata", nil, false],
  ["Fideos spaghetti", nil, false],
  ["Fideos penne", nil, false],
  ["Fideos tallarín", nil, false],
  ["Fideos moñitos", nil, false],
  ["Arroz largo fino", nil, false],
  ["Arroz integral", nil, false],
  ["Arroz yamaní", nil, false],
  ["Quinoa", nil, false],
  ["Lentejas", nil, false],
  ["Garbanzos", nil, false],
  ["Porotos negros", nil, false],
  ["Porotos blancos", nil, false],
  ["Aceite de oliva extra virgen", nil, false],
  ["Aceite de girasol", nil, false],
  ["Aceite de coco", nil, false],
  ["Vinagre de manzana", nil, false],
  ["Vinagre balsámico", nil, false],
  ["Sal gruesa", nil, false],
  ["Sal fina", nil, false],
  ["Pimienta negra", nil, false],
  ["Pimentón dulce", nil, false],
  ["Comino", nil, false],
  ["Orégano seco", nil, false],
  ["Tomillo", nil, false],
  ["Romero", nil, false],
  ["Laurel", nil, false],
  ["Curry", nil, false],
  ["Cúrcuma", nil, false],
  ["Salsa de tomate (lata)", nil, false],
  ["Pasta de tomate", nil, false],
  ["Ketchup", nil, false],
  ["Mostaza", nil, false],
  ["Mayonesa", nil, false],
  ["Salsa de soja", nil, false],
  ["Salsa worcestershire", nil, false],
  ["Harina 0000", nil, false],
  ["Harina integral", nil, false],
  ["Fécula de maíz", nil, false],
  ["Polvo para hornear", nil, false],
  ["Levadura seca", nil, false],
  ["Azúcar blanca", nil, false],
  ["Azúcar negra", nil, false],
  ["Miel", nil, false],
  ["Dulce de leche", nil, false],
  ["Chocolate negro 70%", nil, false],
  ["Chocolate con leche", nil, false],
  ["Cacao en polvo", nil, false],
  ["Café molido", nil, false],
  ["Café instantáneo", nil, false],
  ["Té negro", nil, false],
  ["Té verde", nil, false],
  ["Mate", nil, false],
  ["Leche vegetal de almendras", nil, false],
  ["Leche de avena", nil, false],
  ["Leche de coco", nil, false],
  ["Agua mineral con gas", nil, false],
  ["Agua mineral sin gas", nil, false],
  ["Jugo de naranja", nil, false],
  ["Gaseosa cola", nil, false],
  ["Gaseosa lima limón", nil, false],
  ["Agua tónica", nil, false],
  ["Cerveza artesanal", nil, false],
  ["Vino tinto Malbec", nil, false],
  ["Vino blanco Chardonnay", nil, false],
  ["Papel de aluminio", nil, false],
  ["Film plástico", nil, false],
  ["Bolsas de residuos grandes", nil, false],
  ["Bolsas de residuos chicas", nil, false],
  ["Papel de cocina", nil, false],
  ["Papel higiénico", nil, false],
  ["Detergente", nil, false],
  ["Esponjas de cocina", nil, false],
  ["Lavandina", nil, false],
  ["Desengrasante", nil, false],
  ["Shampoo", nil, false],
  ["Acondicionador", nil, false],
  ["Jabón de tocador", nil, false],
  ["Pasta dental", nil, false],
  ["Hilo dental", nil, false],
].each { |t, d, c| supermercado_del_mes.todo_list_items.create!(title: t, description: d, completed: c) }

pendientes_personales = TodoList.create!(name: "Pendientes personales1")
[
  ["Salir a correr 5km", nil, true],
  ["Hacer yoga por 30 minutostest", "test", true],
  ["Meditar 10 minutos", nil, true],
  ["Leer 30 páginas del libro actual", nil, true],
  ["Llamar a mamá", nil, true],
  ["Llamar al médico para turno", nil, false],
  ["Ir al dentista", nil, true],
  ["Pagar factura de luz", nil, false],
  ["Pagar factura de gas", nil, true],
  ["Pagar tarjeta de crédito", nil, false],
  ["Renovar seguro del auto", nil, true],
  ["Llevar el auto al service", nil, false],
  ["Sacar turno en el banco", nil, true],
  ["Actualizar datos bancarios", nil, false],
  ["Ordenar el armario", nil, true],
  ["Limpiar el baño", nil, false],
  ["Pasar la aspiradora", nil, true],
  ["Lavar ropa", nil, false],
  ["Planchar ropa", nil, true],
  ["Comprar jabón para lavar ropa", nil, false],
  ["Regar las plantas", nil, true],
  ["Podar el jardín", nil, false],
  ["Comprar tierra para macetas", nil, true],
  ["Buscar receta para la cena del viernes", nil, false],
  ["Preparar meal prep del domingo", nil, true],
  ["Reservar restaurante para el aniversario", nil, false],
  ["Comprar regalo de cumpleaños de Pablo", nil, true],
  ["Organizar viaje a Bariloche", nil, false],
  ["Buscar hoteles en Mendoza", nil, true],
  ["Renovar pasaporte", nil, false],
  ["Sacar visa para Europa", nil, true],
  ["Aprender 10 palabras nuevas en inglés", nil, false],
  ["Practicar guitarra 20 minutos", nil, true],
  ["Ver tutorial de acuarela", nil, false],
  ["Terminar el curso de fotografía online", nil, true],
  ["Escribir en el diario", nil, false],
  ["Revisar metas del mes", nil, true],
  ["Actualizar CV", nil, false],
  ["Revisar perfil de LinkedIn", nil, true],
  ["Arreglar la canilla que gotea", nil, false],
  ["Cambiar lamparita del baño", nil, true],
  ["Comprar cortinas para la habitación", nil, false],
  ["Devolver libro a la biblioteca", nil, true],
  ["Hacer donación a Cruz Roja", nil, false],
  ["Organizar fotos del viaje en álbum", nil, true],
  ["test", "111", false],
].each { |t, d, c| pendientes_personales.todo_list_items.create!(title: t, description: d, completed: c) }

libros_para_leer_en_2 = TodoList.create!(name: "Libros para leer en 2026")
[
  ["El nombre del viento — Patrick Rothfuss", nil, true],
  ["El temor de un hombre sabio — Patrick Rothfuss", nil, true],
  ["Dune — Frank Herbert", nil, true],
  ["Dune Messiah — Frank Herbert", nil, true],
  ["Children of Dune — Frank Herbert", nil, true],
  ["Foundation — Isaac Asimov", nil, true],
  ["Foundation and Empire — Isaac Asimov", nil, true],
  ["Second Foundation — Isaac Asimov", nil, true],
  ["Neuromancer — William Gibson", nil, true],
  ["Snow Crash — Neal Stephenson", nil, true],
  ["The Left Hand of Darkness — Ursula K. Le Guin", nil, true],
  ["Ender's Game — Orson Scott Card", nil, true],
  ["The Hitchhiker's Guide to the Galaxy — Douglas Adams", nil, false],
  ["1984 — George Orwell", nil, false],
  ["Brave New World — Aldous Huxley", nil, false],
  ["Fahrenheit 451 — Ray Bradbury", nil, false],
  ["The Martian — Andy Weir", nil, false],
  ["Project Hail Mary — Andy Weir", nil, false],
  ["Three Body Problem — Liu Cixin", nil, false],
  ["The Dark Forest — Liu Cixin", nil, false],
  ["Death's End — Liu Cixin", nil, false],
  ["Recursion — Blake Crouch", nil, false],
  ["Dark Matter — Blake Crouch", nil, false],
  ["Flowers for Algernon — Daniel Keyes", nil, false],
  ["I, Robot — Isaac Asimov", nil, false],
  ["The Caves of Steel — Isaac Asimov", nil, false],
  ["Do Androids Dream of Electric Sheep? — Philip K. Dick", nil, false],
  ["A Scanner Darkly — Philip K. Dick", nil, false],
  ["Ubik — Philip K. Dick", nil, false],
  ["Rendezvous with Rama — Arthur C. Clarke", nil, false],
  ["Childhood's End — Arthur C. Clarke", nil, false],
  ["2001: A Space Odyssey — Arthur C. Clarke", nil, false],
  ["Hyperion — Dan Simmons", nil, false],
  ["The Fall of Hyperion — Dan Simmons", nil, false],
  ["Endymion — Dan Simmons", nil, false],
  ["Old Man's War — John Scalzi", nil, false],
  ["The Forever War — Joe Haldeman", nil, false],
  ["Starship Troopers — Robert A. Heinlein", nil, false],
  ["Stranger in a Strange Land — Robert A. Heinlein", nil, false],
  ["A Fire Upon the Deep — Vernor Vinge", nil, false],
  ["Spin — Robert Charles Wilson", nil, false],
  ["The Road — Cormac McCarthy", nil, false],
  ["Station Eleven — Emily St. John Mandel", nil, false],
  ["The Power — Naomi Alderman", nil, false],
  ["Oryx and Crake — Margaret Atwood", nil, false],
  ["The Dispossessed — Ursula K. Le Guin", nil, false],
  ["A Wizard of Earthsea — Ursula K. Le Guin", nil, false],
  ["The Word for World is Forest — Ursula K. Le Guin", nil, false],
  ["Ancillary Justice — Ann Leckie", nil, false],
  ["A Memory Called Empire — Arkady Martine", nil, false],
  ["Piranesi — Susanna Clarke", nil, false],
  ["Jonathan Strange & Mr Norrell — Susanna Clarke", nil, false],
  ["The Name of the Rose — Umberto Eco", nil, false],
  ["Solaris — Stanisław Lem", nil, false],
  ["The Cyberiad — Stanisław Lem", nil, false],
  ["Never Let Me Go — Kazuo Ishiguro", nil, false],
  ["Klara and the Sun — Kazuo Ishiguro", nil, false],
  ["Exhalation — Ted Chiang", nil, false],
  ["Stories of Your Life and Others — Ted Chiang", nil, false],
  ["Blindsight — Peter Watts", nil, false],
  ["Echopraxia — Peter Watts", nil, false],
  ["Red Mars — Kim Stanley Robinson", nil, false],
  ["Green Mars — Kim Stanley Robinson", nil, false],
  ["Blue Mars — Kim Stanley Robinson", nil, false],
  ["The Long Earth — Terry Pratchett & Stephen Baxter", nil, false],
  ["Good Omens — Terry Pratchett & Neil Gaiman", nil, false],
  ["American Gods — Neil Gaiman", nil, false],
  ["Coraline — Neil Gaiman", nil, false],
  ["The Ocean at the End of the Lane — Neil Gaiman", nil, false],
  ["Stardust — Neil Gaiman", nil, false],
  ["The Way of Kings — Brandon Sanderson", nil, false],
  ["Words of Radiance — Brandon Sanderson", nil, false],
  ["Oathbringer — Brandon Sanderson", nil, false],
  ["Rhythm of War — Brandon Sanderson", nil, false],
  ["Mistborn: The Final Empire — Brandon Sanderson", nil, false],
  ["The Well of Ascension — Brandon Sanderson", nil, false],
  ["The Hero of Ages — Brandon Sanderson", nil, false],
  ["Warbreaker — Brandon Sanderson", nil, false],
  ["Elantris — Brandon Sanderson", nil, false],
  ["The Alloy of Law — Brandon Sanderson", nil, false],
  ["Shadows of Self — Brandon Sanderson", nil, false],
  ["The Bands of Mourning — Brandon Sanderson", nil, false],
  ["A Game of Thrones — George R.R. Martin", nil, false],
  ["A Clash of Kings — George R.R. Martin", nil, false],
  ["A Storm of Swords — George R.R. Martin", nil, false],
  ["A Feast for Crows — George R.R. Martin", nil, false],
  ["A Dance with Dragons — George R.R. Martin", nil, false],
  ["The Fellowship of the Ring — J.R.R. Tolkien", nil, false],
  ["The Two Towers — J.R.R. Tolkien", nil, false],
  ["The Return of the King — J.R.R. Tolkien", nil, false],
  ["The Silmarillion — J.R.R. Tolkien", nil, false],
  ["The Hobbit — J.R.R. Tolkien", nil, false],
  ["Harry Potter y la piedra filosofal — J.K. Rowling", nil, false],
  ["Harry Potter y la cámara secreta — J.K. Rowling", nil, false],
  ["Harry Potter y el prisionero de Azkaban — J.K. Rowling", nil, false],
  ["Harry Potter y el cáliz de fuego — J.K. Rowling", nil, false],
  ["Harry Potter y la orden del Fénix — J.K. Rowling", nil, false],
  ["Harry Potter y el misterio del príncipe — J.K. Rowling", nil, false],
  ["Harry Potter y las reliquias de la muerte — J.K. Rowling", nil, false],
].each { |t, d, c| libros_para_leer_en_2.todo_list_items.create!(title: t, description: d, completed: c) }

proximo_viaje_europa_ = TodoList.create!(name: "Próximo viaje — Europa 2026")
[
  ["Comprar pasajes de avión", nil, true],
  ["Reservar hotel o Airbnb", nil, true],
  ["Conseguir seguro de viaje", nil, true],
  ["Avisar a familia y amigos", "test", true],
  ["Revisar vigencia del pasaporte", nil, true],
  ["Gestionar visa si corresponde", nil, true],
  ["Descargar mapas offline en Google Maps", nil, true],
  ["Guardar itinerario en el teléfono", nil, true],
  ["Hacer lista de qué empacar", nil, true],
  ["Comprar adaptador de corriente", nil, false],
  ["Conseguir moneda local", nil, false],
  ["Avisar al banco del viaje", nil, false],
  ["Desbloquear datos en el exterior con el proveedor", nil, false],
  ["Comprar simcard local para el viaje", nil, false],
  ["Reservar traslado al aeropuerto", nil, false],
  ["Hacer check-in online", nil, false],
  ["Imprimir o guardar boarding pass", nil, false],
  ["Empacar ropa según clima del destino", nil, false],
  ["Empacar cargadores y cables necesarios", nil, false],
  ["Empacar remedios básicos (ibuprofeno, antihistamínico)", nil, false],
  ["Empacar protector solar", nil, false],
  ["Empacar repelente de insectos", nil, false],
  ["Empacar neceser con artículos de higiene", nil, false],
  ["Conseguir guía de viaje del destino", nil, false],
  ["Investigar atracciones principales", nil, false],
  ["Reservar tour guiado por el centro histórico", nil, false],
  ["Reservar entrada al museo principal", nil, false],
  ["Buscar restaurantes bien recomendados", nil, false],
  ["Encontrar mercado local para probar comida típica", nil, false],
  ["Buscar bar con música en vivo", nil, false],
  ["Reservar actividad de senderismo", nil, false],
  ["Alquilar bicicleta para el día", nil, false],
  ["Investigar transporte público local", nil, false],
  ["Comprar tarjeta de transporte", nil, false],
  ["Investigar propinas y costumbres locales", nil, false],
  ["Aprender frases básicas en el idioma local", nil, false],
  ["Descargar app de traducción offline", nil, false],
  ["Cargar Spotify con playlist para el avión", nil, false],
  ["Descargar series o películas offline para el vuelo", nil, false],
  ["Comprar snacks y agua para el aeropuerto", nil, false],
  ["Llegar al aeropuerto con 2.5hs de anticipación", nil, false],
  ["Pasar por migraciones y aduana", nil, false],
  ["Reclamar equipaje en la cinta", nil, false],
  ["Encontrar transporte hacia el alojamiento", nil, false],
  ["Hacer check-in en el alojamiento", nil, false],
  ["Explorar el barrio del alojamiento el primer día", nil, false],
  ["Cambiar moneda en casa de cambio local", nil, false],
  ["Sacar efectivo en cajero si es necesario", nil, false],
  ["Probar el plato típico del lugar", nil, false],
  ["Escribir postales para enviar a casa", nil, false],
  ["Comprar souvenirs para amigos y familia", nil, false],
  ["Hacer backup de fotos en la nube", nil, false],
  ["Hacer check-out del alojamiento", nil, false],
  ["Confirmar reserva del traslado de vuelta", nil, false],
  ["Pasar por duty-free", nil, false],
  ["Escribir reseñas del hotel y restaurantes en TripAdvisor", nil, false],
  ["Ordenar fotos del viaje al volver", nil, false],
  ["Actualizar álbum de Google Photos", nil, false],
  ["Revisar extracto bancario post-viaje", nil, false],
  ["Presentar comprobantes de gastos si corresponde reembolso", nil, false],
].each { |t, d, c| proximo_viaje_europa_.todo_list_items.create!(title: t, description: d, completed: c) }

recetas_para_probar = TodoList.create!(name: "Recetas para probar")
[
  ["Risotto de hongos", "Rehoga cebolla y ajo. Agrega arroz arborio, vino blanco, caldo caliente de a poco. Incorpora hongos salteados y termina con manteca y parmesano.", false],
  ["Tarta de zapallitos", "Saltea zapallitos con cebolla. Mezcla con huevos, queso y crema. Vierte en molde con masa brisée precocida. Hornear 35 min a 180°C.", false],
  ["Milanesas a la napolitana", "Freír milanesas. Cubrir con salsa de tomate, jamón y mozzarella. Gratinar en el horno hasta derretir el queso.", false],
  ["Pasta al pesto", "Procesar albahaca, ajo, piñones y parmesano con aceite de oliva. Mezclar con pasta recién cocida.", false],
  ["Locro criollo", "Cocinar maíz y porotos hidratados. Agregar mondongo, chorizo colorado, costillas, zapallo y papas. Cocinar a fuego lento 2 horas.", false],
  ["Empanadas tucumanas", "Saltear carne picada a cuchillo con cebolla, cebollita de verdeo, pimentón y comino. Rellenar discos y repulgar. Hornear 20 min.", false],
  ["Asado con cuero", "Salar el cuero la noche anterior. Cocinar sobre brasas a fuego muy bajo durante 4-6 horas hasta que la piel esté crujiente.", false],
  ["Chipá", "Mezclar almidón de mandioca, queso Paraguay, huevos, manteca y leche. Formar bollitos. Hornear 15 min a 200°C.", false],
  ["Humita en chala", "Procesar choclo crudo con cebolla, pimiento y queso. Envolver en chalas, atar y cocinar en agua hirviendo 40 minutos.", false],
  ["Cazuela de mariscos", "Saltear cebolla, ajo, pimiento y tomate. Agregar caldo de pescado, papas y mariscos varios. Cocinar 15 min y servir con arroz.", false],
  ["Ceviche", "Cortar pescado blanco en cubos. Marinar en jugo de limón 15 minutos. Agregar cebolla morada, cilantro, ají amarillo y sal.", false],
  ["Tacos al pastor", "Marinar cerdo con achiote, naranja y especias. Cocinar en sartén. Servir en tortilla con piña, cebolla y cilantro.", false],
  ["Ramen casero", "Preparar caldo dashi con kombu y katsuobushi. Agregar tare de soja y mirin. Servir con fideos, chashu, huevo marinado y nori.", false],
  ["Stir fry de vegetales", "Saltear en wok a fuego alto: brócoli, zanahoria, pimiento, arvejitas y baby corn. Condimentar con salsa de soja, aceite de sésamo y jengibre.", false],
  ["Shakshuka", "Saltear cebolla, pimiento y ajo con comino y pimentón. Agregar tomates triturados. Hacer pozos y romper huevos dentro. Cocinar tapado 8 minutos.", false],
  ["Börek de espinaca", "Saltear espinaca con cebolla y queso feta. Rellenar capas de masa filo pinceladas con manteca. Hornear hasta dorar.", false],
  ["Butter chicken", "Marinar pollo en yogur y especias. Sellar y reservar. Preparar salsa con tomate, cebolla, ajo, jengibre, garam masala y crema. Unir y cocinar 20 min.", false],
  ["Pad thai", "Saltear fideos de arroz con camarones, huevo revuelto, brotes de soja y cebollita. Condimentar con tamarindo, fish sauce y azúcar. Terminar con maní y lima.", false],
  ["Goulash húngaro", "Dorar carne con cebolla y ajo. Agregar pimentón húngaro, tomates y caldo. Cocinar 2 horas a fuego lento con papas.", false],
  ["Moussaka", "Freír berenjenas. Preparar carne molida con tomate y canela. Hacer bechamel. Alternar capas en molde y gratinar 45 min.", false],
  ["Focaccia", "Mezclar harina, agua, sal, levadura y aceite. Dejar leudar 1 hora. Estirar en molde aceitado, hundir dedos, cubrir con romero y sal gruesa. Hornear 25 min.", false],
  ["Cheesecake de maracuyá", "Batir queso crema con azúcar y crema. Agregar gelatina disuelta. Verter sobre base de galletitas. Cubrir con coulis de maracuyá. Refrigerar 4 horas.", false],
  ["Brownie intenso", "Derretir chocolate negro con manteca. Agregar azúcar, huevos y extracto de vainilla. Incorporar harina y sal. Hornear 22 min a 170°C (debe quedar húmedo).", false],
  ["Churros con chocolate", "Hervir agua, manteca y sal. Incorporar harina de golpe. Manga con boquilla estrellada, freír en aceite caliente. Servir con chocolate caliente espeso.", false],
  ["Alfajores de maizena", "Batir manteca con azúcar impalpable. Agregar yemas y ralladura de limón. Incorporar fécula y harina. Formar bolillas, aplastar, hornear 10 min. Unir con dulce de leche y rebozar en coco rallado.", false],
].each { |t, d, c| recetas_para_probar.todo_list_items.create!(title: t, description: d, completed: c) }

inventario_completo_d = TodoList.create!(name: "Inventario completo del almacén")
[
  ["[Lácteos] Leche entera (1L) — lote 1", nil, true],
  ["[Carnicería] Yogur natural — lote 1", nil, false],
  ["[Bebidas] Yogur griego — lote 1", nil, false],
  ["[Limpieza] Queso mozzarella — lote 1", nil, false],
  ["[Panadería] Queso cheddar — lote 1", nil, false],
  ["[Lácteos] Queso brie — lote 1", nil, false],
  ["[Verdulería] Queso parmesano — lote 1", nil, true],
  ["[Carnicería] Manteca sin sal — lote 1", nil, false],
  ["[Bebidas] Crema de leche — lote 1", nil, false],
  ["[Limpieza] Huevos (docena) — lote 1", nil, false],
  ["[Panadería] Claras de huevo — lote 1", nil, false],
  ["[Lácteos] Pan de campo — lote 1", nil, false],
  ["[Verdulería] Pan integral — lote 1", nil, false],
  ["[Carnicería] Pan de molde — lote 1", nil, true],
  ["[Bebidas] Medialunas — lote 1", nil, false],
  ["[Limpieza] Manzanas Granny Smith — lote 1", nil, false],
  ["[Panadería] Manzanas Red Delicious — lote 1", nil, false],
  ["[Lácteos] Peras Williams — lote 1", nil, false],
  ["[Verdulería] Duraznos — lote 1", nil, false],
  ["[Carnicería] Bananas — lote 1", nil, false],
  ["[Bebidas] Naranjas — lote 1", nil, true],
  ["[Limpieza] Mandarinas — lote 1", nil, false],
  ["[Panadería] Limones — lote 1", nil, false],
  ["[Lácteos] Pomelos — lote 1", nil, false],
  ["[Verdulería] Uvas verdes — lote 1", nil, false],
  ["[Carnicería] Uvas negras — lote 1", nil, false],
  ["[Bebidas] Frutillas — lote 1", nil, false],
  ["[Limpieza] Frambuesas — lote 1", nil, true],
  ["[Panadería] Arándanos — lote 1", nil, false],
  ["[Lácteos] Kiwi — lote 1", nil, false],
  ["[Verdulería] Melón — lote 1", nil, false],
  ["[Carnicería] Sandía — lote 1", nil, false],
  ["[Bebidas] Mango — lote 1", nil, false],
  ["[Limpieza] Piña — lote 1", nil, false],
  ["[Panadería] Ananá en lata — lote 1", nil, true],
  ["[Lácteos] Dátiles — lote 1", nil, false],
  ["[Verdulería] Tomates cherry — lote 1", nil, false],
  ["[Carnicería] Tomates perita — lote 1", nil, false],
  ["[Bebidas] Tomates redondos — lote 1", nil, false],
  ["[Limpieza] Lechuga mantecosa — lote 1", nil, false],
  ["[Panadería] Lechuga iceberg — lote 1", nil, false],
  ["[Lácteos] Rúcula — lote 1", nil, true],
  ["[Verdulería] Espinaca — lote 1", nil, false],
  ["[Carnicería] Zanahoria — lote 1", nil, false],
  ["[Bebidas] Zucchini — lote 1", nil, false],
  ["[Limpieza] Berenjena — lote 1", nil, false],
  ["[Panadería] Pimiento rojo — lote 1", nil, false],
  ["[Lácteos] Pimiento verde — lote 1", nil, false],
  ["[Verdulería] Pimiento amarillo — lote 1", nil, true],
  ["[Carnicería] Brócoli — lote 1", nil, false],
  ["[Bebidas] Coliflor — lote 1", nil, false],
  ["[Limpieza] Repollo blanco — lote 1", nil, false],
  ["[Panadería] Repollo morado — lote 1", nil, false],
  ["[Lácteos] Cebolla blanca — lote 1", nil, false],
  ["[Verdulería] Cebolla morada — lote 1", nil, false],
  ["[Carnicería] Cebolla de verdeo — lote 1", nil, true],
  ["[Bebidas] Ajo — lote 1", nil, false],
  ["[Limpieza] Jengibre — lote 1", nil, false],
  ["[Panadería] Apio — lote 1", nil, false],
  ["[Lácteos] Puerro — lote 1", nil, false],
  ["[Verdulería] Remolacha — lote 1", nil, false],
  ["[Carnicería] Choclo — lote 1", nil, false],
  ["[Bebidas] Arvejas frescas — lote 1", nil, true],
  ["[Limpieza] Chaucha — lote 1", nil, false],
  ["[Panadería] Papas — lote 1", nil, false],
  ["[Lácteos] Papas andinas — lote 1", nil, false],
  ["[Verdulería] Batata — lote 1", nil, false],
  ["[Carnicería] Mandioca — lote 1", nil, false],
  ["[Bebidas] Pechuga de pollo — lote 1", nil, false],
  ["[Limpieza] Muslo de pollo — lote 1", nil, true],
  ["[Panadería] Pollo entero — lote 1", nil, false],
  ["[Lácteos] Hamburguesas de pollo — lote 1", nil, false],
  ["[Verdulería] Carne picada — lote 1", nil, false],
  ["[Carnicería] Bife de chorizo — lote 1", nil, false],
  ["[Bebidas] Asado — lote 1", nil, false],
  ["[Limpieza] Costillas — lote 1", nil, false],
  ["[Panadería] Vacío — lote 1", nil, true],
  ["[Lácteos] Lomo — lote 1", nil, false],
  ["[Verdulería] Milanesas de ternera — lote 1", nil, false],
  ["[Carnicería] Salchicha parrillera — lote 1", nil, false],
  ["[Bebidas] Salmon — lote 1", nil, false],
  ["[Limpieza] Merluza filetes — lote 1", nil, false],
  ["[Panadería] Atún en lata — lote 1", nil, false],
  ["[Lácteos] Sardinas en lata — lote 1", nil, true],
  ["[Verdulería] Fideos spaghetti — lote 1", nil, false],
  ["[Carnicería] Fideos penne — lote 1", nil, false],
  ["[Bebidas] Fideos tallarín — lote 1", nil, false],
  ["[Limpieza] Fideos moñitos — lote 1", nil, false],
  ["[Panadería] Arroz largo fino — lote 1", nil, false],
  ["[Lácteos] Arroz integral — lote 1", nil, false],
  ["[Verdulería] Arroz yamaní — lote 1", nil, true],
  ["[Carnicería] Quinoa — lote 1", nil, false],
  ["[Bebidas] Lentejas — lote 1", nil, false],
  ["[Limpieza] Garbanzos — lote 1", nil, false],
  ["[Panadería] Porotos negros — lote 1", nil, false],
  ["[Lácteos] Porotos blancos — lote 1", nil, false],
  ["[Verdulería] Aceite de oliva extra virgen — lote 1", nil, false],
  ["[Carnicería] Aceite de girasol — lote 1", nil, true],
  ["[Bebidas] Aceite de coco — lote 1", nil, false],
  ["[Limpieza] Vinagre de manzana — lote 1", nil, false],
  ["[Panadería] Vinagre balsámico — lote 1", nil, false],
  ["[Lácteos] Sal gruesa — lote 1", nil, false],
  ["[Verdulería] Sal fina — lote 1", nil, false],
  ["[Carnicería] Pimienta negra — lote 1", nil, false],
  ["[Bebidas] Pimentón dulce — lote 1", nil, true],
  ["[Limpieza] Comino — lote 1", nil, false],
  ["[Panadería] Orégano seco — lote 1", nil, false],
  ["[Lácteos] Tomillo — lote 1", nil, false],
  ["[Verdulería] Romero — lote 1", nil, false],
  ["[Carnicería] Laurel — lote 1", nil, false],
  ["[Bebidas] Curry — lote 1", nil, false],
  ["[Limpieza] Cúrcuma — lote 1", nil, true],
  ["[Panadería] Salsa de tomate (lata) — lote 1", nil, false],
  ["[Lácteos] Pasta de tomate — lote 1", nil, false],
  ["[Verdulería] Ketchup — lote 1", nil, false],
  ["[Carnicería] Mostaza — lote 1", nil, false],
  ["[Bebidas] Mayonesa — lote 1", nil, false],
  ["[Limpieza] Salsa de soja — lote 1", nil, false],
  ["[Panadería] Salsa worcestershire — lote 1", nil, true],
  ["[Lácteos] Harina 0000 — lote 1", nil, false],
  ["[Verdulería] Harina integral — lote 1", nil, false],
  ["[Carnicería] Fécula de maíz — lote 1", nil, false],
  ["[Bebidas] Polvo para hornear — lote 1", nil, false],
  ["[Limpieza] Levadura seca — lote 1", nil, false],
  ["[Panadería] Azúcar blanca — lote 1", nil, false],
  ["[Lácteos] Azúcar negra — lote 1", nil, true],
  ["[Verdulería] Miel — lote 1", nil, false],
  ["[Carnicería] Dulce de leche — lote 1", nil, false],
  ["[Bebidas] Chocolate negro 70% — lote 1", nil, false],
  ["[Limpieza] Chocolate con leche — lote 1", nil, false],
  ["[Panadería] Cacao en polvo — lote 1", nil, false],
  ["[Lácteos] Café molido — lote 1", nil, false],
  ["[Verdulería] Café instantáneo — lote 1", nil, true],
  ["[Carnicería] Té negro — lote 1", nil, false],
  ["[Bebidas] Té verde — lote 1", nil, false],
  ["[Limpieza] Mate — lote 1", nil, false],
  ["[Panadería] Leche vegetal de almendras — lote 1", nil, false],
  ["[Lácteos] Leche de avena — lote 1", nil, false],
  ["[Verdulería] Leche de coco — lote 1", nil, false],
  ["[Carnicería] Agua mineral con gas — lote 1", nil, true],
  ["[Bebidas] Agua mineral sin gas — lote 1", nil, false],
  ["[Limpieza] Jugo de naranja — lote 1", nil, false],
  ["[Panadería] Gaseosa cola — lote 1", nil, false],
  ["[Lácteos] Gaseosa lima limón — lote 1", nil, false],
  ["[Verdulería] Agua tónica — lote 1", nil, false],
  ["[Carnicería] Cerveza artesanal — lote 1", nil, false],
  ["[Bebidas] Vino tinto Malbec — lote 1", nil, true],
  ["[Limpieza] Vino blanco Chardonnay — lote 1", nil, false],
  ["[Panadería] Papel de aluminio — lote 1", nil, false],
  ["[Lácteos] Film plástico — lote 1", nil, false],
  ["[Verdulería] Bolsas de residuos grandes — lote 1", nil, false],
  ["[Carnicería] Bolsas de residuos chicas — lote 1", nil, false],
  ["[Bebidas] Papel de cocina — lote 1", nil, false],
  ["[Limpieza] Papel higiénico — lote 1", nil, true],
  ["[Panadería] Detergente — lote 1", nil, false],
  ["[Lácteos] Esponjas de cocina — lote 1", nil, false],
  ["[Verdulería] Lavandina — lote 1", nil, false],
  ["[Carnicería] Desengrasante — lote 1", nil, false],
  ["[Bebidas] Shampoo — lote 1", nil, false],
  ["[Limpieza] Acondicionador — lote 1", nil, false],
  ["[Panadería] Jabón de tocador — lote 1", nil, true],
  ["[Lácteos] Pasta dental — lote 1", nil, false],
  ["[Verdulería] Hilo dental — lote 1", nil, false],
  ["[Carnicería] Leche entera (1L) — lote 2", nil, false],
  ["[Bebidas] Leche descremada (1L) — lote 2", nil, false],
  ["[Limpieza] Yogur natural — lote 2", nil, false],
  ["[Panadería] Yogur griego — lote 2", nil, false],
  ["[Lácteos] Queso mozzarella — lote 2", nil, true],
  ["[Verdulería] Queso cheddar — lote 2", nil, false],
  ["[Carnicería] Queso brie — lote 2", nil, false],
  ["[Bebidas] Queso parmesano — lote 2", nil, false],
  ["[Limpieza] Manteca sin sal — lote 2", nil, false],
  ["[Panadería] Crema de leche — lote 2", nil, false],
  ["[Lácteos] Huevos (docena) — lote 2", nil, false],
  ["[Verdulería] Claras de huevo — lote 2", nil, true],
  ["[Carnicería] Pan de campo — lote 2", nil, false],
  ["[Bebidas] Pan integral — lote 2", nil, false],
  ["[Limpieza] Pan de molde — lote 2", nil, false],
  ["[Panadería] Medialunas — lote 2", nil, false],
  ["[Lácteos] Manzanas Granny Smith — lote 2", nil, false],
  ["[Verdulería] Manzanas Red Delicious — lote 2", nil, false],
  ["[Carnicería] Peras Williams — lote 2", nil, true],
  ["[Bebidas] Duraznos — lote 2", nil, false],
  ["[Limpieza] Bananas — lote 2", nil, false],
  ["[Panadería] Naranjas — lote 2", nil, false],
  ["[Lácteos] Mandarinas — lote 2", nil, false],
  ["[Verdulería] Limones — lote 2", nil, false],
  ["[Carnicería] Pomelos — lote 2", nil, false],
  ["[Bebidas] Uvas verdes — lote 2", nil, true],
  ["[Limpieza] Uvas negras — lote 2", nil, false],
  ["[Panadería] Frutillas — lote 2", nil, false],
  ["[Lácteos] Frambuesas — lote 2", nil, false],
  ["[Verdulería] Arándanos — lote 2", nil, false],
  ["[Carnicería] Kiwi — lote 2", nil, false],
  ["[Bebidas] Melón — lote 2", nil, false],
  ["[Limpieza] Sandía — lote 2", nil, true],
  ["[Panadería] Mango — lote 2", nil, false],
  ["[Lácteos] Piña — lote 2", nil, false],
  ["[Verdulería] Ananá en lata — lote 2", nil, false],
  ["[Carnicería] Dátiles — lote 2", nil, false],
  ["[Bebidas] Tomates cherry — lote 2", nil, false],
  ["[Limpieza] Tomates perita — lote 2", nil, false],
  ["[Panadería] Tomates redondos — lote 2", nil, true],
  ["[Lácteos] Lechuga mantecosa — lote 2", nil, false],
  ["[Verdulería] Lechuga iceberg — lote 2", nil, false],
  ["[Carnicería] Rúcula — lote 2", nil, false],
  ["[Bebidas] Espinaca — lote 2", nil, false],
  ["[Limpieza] Zanahoria — lote 2", nil, false],
  ["[Panadería] Zucchini — lote 2", nil, false],
  ["[Lácteos] Berenjena — lote 2", nil, true],
  ["[Verdulería] Pimiento rojo — lote 2", nil, false],
  ["[Carnicería] Pimiento verde — lote 2", nil, false],
  ["[Bebidas] Pimiento amarillo — lote 2", nil, false],
  ["[Limpieza] Brócoli — lote 2", nil, false],
  ["[Panadería] Coliflor — lote 2", nil, false],
  ["[Lácteos] Repollo blanco — lote 2", nil, false],
  ["[Verdulería] Repollo morado — lote 2", nil, true],
  ["[Carnicería] Cebolla blanca — lote 2", nil, false],
  ["[Bebidas] Cebolla morada — lote 2", nil, false],
  ["[Limpieza] Cebolla de verdeo — lote 2", nil, false],
  ["[Panadería] Ajo — lote 2", nil, false],
  ["[Lácteos] Jengibre — lote 2", nil, false],
  ["[Verdulería] Apio — lote 2", nil, false],
  ["[Carnicería] Puerro — lote 2", nil, true],
  ["[Bebidas] Remolacha — lote 2", nil, false],
  ["[Limpieza] Choclo — lote 2", nil, false],
  ["[Panadería] Arvejas frescas — lote 2", nil, false],
  ["[Lácteos] Chaucha — lote 2", nil, false],
  ["[Verdulería] Papas — lote 2", nil, false],
  ["[Carnicería] Papas andinas — lote 2", nil, false],
  ["[Bebidas] Batata — lote 2", nil, true],
  ["[Limpieza] Mandioca — lote 2", nil, false],
  ["[Panadería] Pechuga de pollo — lote 2", nil, false],
  ["[Lácteos] Muslo de pollo — lote 2", nil, false],
  ["[Verdulería] Pollo entero — lote 2", nil, false],
  ["[Carnicería] Hamburguesas de pollo — lote 2", nil, false],
  ["[Bebidas] Carne picada — lote 2", nil, false],
  ["[Limpieza] Bife de chorizo — lote 2", nil, true],
  ["[Panadería] Asado — lote 2", nil, false],
  ["[Lácteos] Costillas — lote 2", nil, false],
  ["[Verdulería] Vacío — lote 2", nil, false],
  ["[Carnicería] Lomo — lote 2", nil, false],
  ["[Bebidas] Milanesas de ternera — lote 2", nil, false],
  ["[Limpieza] Salchicha parrillera — lote 2", nil, false],
  ["[Panadería] Salmon — lote 2", nil, true],
  ["[Lácteos] Merluza filetes — lote 2", nil, false],
  ["[Verdulería] Atún en lata — lote 2", nil, false],
  ["[Carnicería] Sardinas en lata — lote 2", nil, false],
  ["[Bebidas] Fideos spaghetti — lote 2", nil, false],
  ["[Limpieza] Fideos penne — lote 2", nil, false],
  ["[Panadería] Fideos tallarín — lote 2", nil, false],
  ["[Lácteos] Fideos moñitos — lote 2", nil, true],
  ["[Verdulería] Arroz largo fino — lote 2", nil, false],
  ["[Carnicería] Arroz integral — lote 2", nil, false],
  ["[Bebidas] Arroz yamaní — lote 2", nil, false],
  ["[Limpieza] Quinoa — lote 2", nil, false],
  ["[Panadería] Lentejas — lote 2", nil, false],
  ["[Lácteos] Garbanzos — lote 2", nil, false],
  ["[Verdulería] Porotos negros — lote 2", nil, true],
  ["[Carnicería] Porotos blancos — lote 2", nil, false],
  ["[Bebidas] Aceite de oliva extra virgen — lote 2", nil, false],
  ["[Limpieza] Aceite de girasol — lote 2", nil, false],
  ["[Panadería] Aceite de coco — lote 2", nil, false],
  ["[Lácteos] Vinagre de manzana — lote 2", nil, false],
  ["[Verdulería] Vinagre balsámico — lote 2", nil, false],
  ["[Carnicería] Sal gruesa — lote 2", nil, true],
  ["[Bebidas] Sal fina — lote 2", nil, false],
  ["[Limpieza] Pimienta negra — lote 2", nil, false],
  ["[Panadería] Pimentón dulce — lote 2", nil, false],
  ["[Lácteos] Comino — lote 2", nil, false],
  ["[Verdulería] Orégano seco — lote 2", nil, false],
  ["[Carnicería] Tomillo — lote 2", nil, false],
  ["[Bebidas] Romero — lote 2", nil, true],
  ["[Limpieza] Laurel — lote 2", nil, false],
  ["[Panadería] Curry — lote 2", nil, false],
  ["[Lácteos] Cúrcuma — lote 2", nil, false],
  ["[Verdulería] Salsa de tomate (lata) — lote 2", nil, false],
  ["[Carnicería] Pasta de tomate — lote 2", nil, false],
  ["[Bebidas] Ketchup — lote 2", nil, false],
  ["[Limpieza] Mostaza — lote 2", nil, true],
  ["[Panadería] Mayonesa — lote 2", nil, false],
  ["[Lácteos] Salsa de soja — lote 2", nil, false],
  ["[Verdulería] Salsa worcestershire — lote 2", nil, false],
  ["[Carnicería] Harina 0000 — lote 2", nil, false],
  ["[Bebidas] Harina integral — lote 2", nil, false],
  ["[Limpieza] Fécula de maíz — lote 2", nil, false],
  ["[Panadería] Polvo para hornear — lote 2", nil, true],
  ["[Lácteos] Levadura seca — lote 2", nil, false],
  ["[Verdulería] Azúcar blanca — lote 2", nil, false],
  ["[Carnicería] Azúcar negra — lote 2", nil, false],
  ["[Bebidas] Miel — lote 2", nil, false],
  ["[Limpieza] Dulce de leche — lote 2", nil, false],
  ["[Panadería] Chocolate negro 70% — lote 2", nil, false],
  ["[Lácteos] Chocolate con leche — lote 2", nil, true],
  ["[Verdulería] Cacao en polvo — lote 2", nil, false],
  ["[Carnicería] Café molido — lote 2", nil, false],
  ["[Bebidas] Café instantáneo — lote 2", nil, false],
  ["[Limpieza] Té negro — lote 2", nil, false],
  ["[Panadería] Té verde — lote 2", nil, false],
  ["[Lácteos] Mate — lote 2", nil, false],
  ["[Verdulería] Leche vegetal de almendras — lote 2", nil, true],
  ["[Carnicería] Leche de avena — lote 2", nil, false],
  ["[Bebidas] Leche de coco — lote 2", nil, false],
  ["[Limpieza] Agua mineral con gas — lote 2", nil, false],
  ["[Panadería] Agua mineral sin gas — lote 2", nil, false],
  ["[Lácteos] Jugo de naranja — lote 2", nil, false],
  ["[Verdulería] Gaseosa cola — lote 2", nil, false],
  ["[Carnicería] Gaseosa lima limón — lote 2", nil, true],
  ["[Bebidas] Agua tónica — lote 2", nil, false],
  ["[Limpieza] Cerveza artesanal — lote 2", nil, false],
  ["[Panadería] Vino tinto Malbec — lote 2", nil, false],
  ["[Lácteos] Vino blanco Chardonnay — lote 2", nil, false],
  ["[Verdulería] Papel de aluminio — lote 2", nil, false],
  ["[Carnicería] Film plástico — lote 2", nil, false],
  ["[Bebidas] Bolsas de residuos grandes — lote 2", nil, true],
  ["[Limpieza] Bolsas de residuos chicas — lote 2", nil, false],
  ["[Panadería] Papel de cocina — lote 2", nil, false],
  ["[Lácteos] Papel higiénico — lote 2", nil, false],
  ["[Verdulería] Detergente — lote 2", nil, false],
  ["[Carnicería] Esponjas de cocina — lote 2", nil, false],
  ["[Bebidas] Lavandina — lote 2", nil, false],
  ["[Limpieza] Desengrasante — lote 2", nil, true],
  ["[Panadería] Shampoo — lote 2", nil, false],
  ["[Lácteos] Acondicionador — lote 2", nil, false],
  ["[Verdulería] Jabón de tocador — lote 2", nil, false],
  ["[Carnicería] Pasta dental — lote 2", nil, false],
  ["[Bebidas] Hilo dental — lote 2", nil, false],
  ["[Limpieza] Leche entera (1L) — lote 3", nil, false],
  ["[Panadería] Leche descremada (1L) — lote 3", nil, true],
  ["[Lácteos] Yogur natural — lote 3", nil, false],
  ["[Verdulería] Yogur griego — lote 3", nil, false],
  ["[Carnicería] Queso mozzarella — lote 3", nil, false],
  ["[Bebidas] Queso cheddar — lote 3", nil, false],
  ["[Limpieza] Queso brie — lote 3", nil, false],
  ["[Panadería] Queso parmesano — lote 3", nil, false],
  ["[Lácteos] Manteca sin sal — lote 3", nil, true],
  ["[Verdulería] Crema de leche — lote 3", nil, false],
  ["[Carnicería] Huevos (docena) — lote 3", nil, false],
  ["[Bebidas] Claras de huevo — lote 3", nil, false],
  ["[Limpieza] Pan de campo — lote 3", nil, false],
  ["[Panadería] Pan integral — lote 3", nil, false],
  ["[Lácteos] Pan de molde — lote 3", nil, false],
  ["[Verdulería] Medialunas — lote 3", nil, true],
  ["[Carnicería] Manzanas Granny Smith — lote 3", nil, false],
  ["[Bebidas] Manzanas Red Delicious — lote 3", nil, false],
  ["[Limpieza] Peras Williams — lote 3", nil, false],
  ["[Panadería] Duraznos — lote 3", nil, false],
  ["[Lácteos] Bananas — lote 3", nil, false],
  ["[Verdulería] Naranjas — lote 3", nil, false],
  ["[Carnicería] Mandarinas — lote 3", nil, true],
  ["[Bebidas] Limones — lote 3", nil, false],
  ["[Limpieza] Pomelos — lote 3", nil, false],
  ["[Panadería] Uvas verdes — lote 3", nil, false],
  ["[Lácteos] Uvas negras — lote 3", nil, false],
  ["[Verdulería] Frutillas — lote 3", nil, false],
  ["[Carnicería] Frambuesas — lote 3", nil, false],
  ["[Bebidas] Arándanos — lote 3", nil, true],
  ["[Limpieza] Kiwi — lote 3", nil, false],
  ["[Panadería] Melón — lote 3", nil, false],
  ["[Lácteos] Sandía — lote 3", nil, false],
  ["[Verdulería] Mango — lote 3", nil, false],
  ["[Carnicería] Piña — lote 3", nil, false],
  ["[Bebidas] Ananá en lata — lote 3", nil, false],
  ["[Limpieza] Dátiles — lote 3", nil, true],
  ["[Panadería] Tomates cherry — lote 3", nil, false],
  ["[Lácteos] Tomates perita — lote 3", nil, false],
  ["[Verdulería] Tomates redondos — lote 3", nil, false],
  ["[Carnicería] Lechuga mantecosa — lote 3", nil, false],
  ["[Bebidas] Lechuga iceberg — lote 3", nil, false],
  ["[Limpieza] Rúcula — lote 3", nil, false],
  ["[Panadería] Espinaca — lote 3", nil, true],
  ["[Lácteos] Zanahoria — lote 3", nil, false],
  ["[Verdulería] Zucchini — lote 3", nil, false],
  ["[Carnicería] Berenjena — lote 3", nil, false],
  ["[Bebidas] Pimiento rojo — lote 3", nil, false],
  ["[Limpieza] Pimiento verde — lote 3", nil, false],
  ["[Panadería] Pimiento amarillo — lote 3", nil, false],
  ["[Lácteos] Brócoli — lote 3", nil, true],
  ["[Verdulería] Coliflor — lote 3", nil, false],
  ["[Carnicería] Repollo blanco — lote 3", nil, false],
  ["[Bebidas] Repollo morado — lote 3", nil, false],
  ["[Limpieza] Cebolla blanca — lote 3", nil, false],
  ["[Panadería] Cebolla morada — lote 3", nil, false],
  ["[Lácteos] Cebolla de verdeo — lote 3", nil, false],
  ["[Verdulería] Ajo — lote 3", nil, true],
  ["[Carnicería] Jengibre — lote 3", nil, false],
  ["[Bebidas] Apio — lote 3", nil, false],
  ["[Limpieza] Puerro — lote 3", nil, false],
  ["[Panadería] Remolacha — lote 3", nil, false],
  ["[Lácteos] Choclo — lote 3", nil, false],
  ["[Verdulería] Arvejas frescas — lote 3", nil, false],
  ["[Carnicería] Chaucha — lote 3", nil, true],
  ["[Bebidas] Papas — lote 3", nil, false],
  ["[Limpieza] Papas andinas — lote 3", nil, false],
  ["[Panadería] Batata — lote 3", nil, false],
  ["[Lácteos] Mandioca — lote 3", nil, false],
  ["[Verdulería] Pechuga de pollo — lote 3", nil, false],
  ["[Carnicería] Muslo de pollo — lote 3", nil, false],
  ["[Bebidas] Pollo entero — lote 3", nil, true],
  ["[Limpieza] Hamburguesas de pollo — lote 3", nil, false],
  ["[Panadería] Carne picada — lote 3", nil, false],
  ["[Lácteos] Bife de chorizo — lote 3", nil, false],
  ["[Verdulería] Asado — lote 3", nil, false],
  ["[Carnicería] Costillas — lote 3", nil, false],
  ["[Bebidas] Vacío — lote 3", nil, false],
  ["[Limpieza] Lomo — lote 3", nil, true],
  ["[Panadería] Milanesas de ternera — lote 3", nil, false],
  ["[Lácteos] Salchicha parrillera — lote 3", nil, false],
  ["[Verdulería] Salmon — lote 3", nil, false],
  ["[Carnicería] Merluza filetes — lote 3", nil, false],
  ["[Bebidas] Atún en lata — lote 3", nil, false],
  ["[Limpieza] Sardinas en lata — lote 3", nil, false],
  ["[Panadería] Fideos spaghetti — lote 3", nil, true],
  ["[Lácteos] Fideos penne — lote 3", nil, false],
  ["[Verdulería] Fideos tallarín — lote 3", nil, false],
  ["[Carnicería] Fideos moñitos — lote 3", nil, false],
  ["[Bebidas] Arroz largo fino — lote 3", nil, false],
  ["[Limpieza] Arroz integral — lote 3", nil, false],
  ["[Panadería] Arroz yamaní — lote 3", nil, false],
  ["[Lácteos] Quinoa — lote 3", nil, true],
  ["[Verdulería] Lentejas — lote 3", nil, false],
  ["[Carnicería] Garbanzos — lote 3", nil, false],
  ["[Bebidas] Porotos negros — lote 3", nil, false],
  ["[Limpieza] Porotos blancos — lote 3", nil, false],
  ["[Panadería] Aceite de oliva extra virgen — lote 3", nil, false],
  ["[Lácteos] Aceite de girasol — lote 3", nil, false],
  ["[Verdulería] Aceite de coco — lote 3", nil, true],
  ["[Carnicería] Vinagre de manzana — lote 3", nil, false],
  ["[Bebidas] Vinagre balsámico — lote 3", nil, false],
  ["[Limpieza] Sal gruesa — lote 3", nil, false],
  ["[Panadería] Sal fina — lote 3", nil, false],
  ["[Lácteos] Pimienta negra — lote 3", nil, false],
  ["[Verdulería] Pimentón dulce — lote 3", nil, false],
  ["[Carnicería] Comino — lote 3", nil, true],
  ["[Bebidas] Orégano seco — lote 3", nil, false],
  ["[Limpieza] Tomillo — lote 3", nil, false],
  ["[Panadería] Romero — lote 3", nil, false],
  ["[Lácteos] Laurel — lote 3", nil, false],
  ["[Verdulería] Curry — lote 3", nil, false],
  ["[Carnicería] Cúrcuma — lote 3", nil, false],
  ["[Bebidas] Salsa de tomate (lata) — lote 3", nil, true],
  ["[Limpieza] Pasta de tomate — lote 3", nil, false],
  ["[Panadería] Ketchup — lote 3", nil, false],
  ["[Lácteos] Mostaza — lote 3", nil, false],
  ["[Verdulería] Mayonesa — lote 3", nil, false],
  ["[Carnicería] Salsa de soja — lote 3", nil, false],
  ["[Bebidas] Salsa worcestershire — lote 3", nil, false],
  ["[Limpieza] Harina 0000 — lote 3", nil, true],
  ["[Panadería] Harina integral — lote 3", nil, false],
  ["[Lácteos] Fécula de maíz — lote 3", nil, false],
  ["[Verdulería] Polvo para hornear — lote 3", nil, false],
  ["[Carnicería] Levadura seca — lote 3", nil, false],
  ["[Bebidas] Azúcar blanca — lote 3", nil, false],
  ["[Limpieza] Azúcar negra — lote 3", nil, false],
  ["[Panadería] Miel — lote 3", nil, true],
  ["[Lácteos] Dulce de leche — lote 3", nil, false],
  ["[Verdulería] Chocolate negro 70% — lote 3", nil, false],
  ["[Carnicería] Chocolate con leche — lote 3", nil, false],
  ["[Bebidas] Cacao en polvo — lote 3", nil, false],
  ["[Limpieza] Café molido — lote 3", nil, false],
  ["[Panadería] Café instantáneo — lote 3", nil, false],
  ["[Lácteos] Té negro — lote 3", nil, true],
  ["[Verdulería] Té verde — lote 3", nil, false],
  ["[Carnicería] Mate — lote 3", nil, false],
  ["[Bebidas] Leche vegetal de almendras — lote 3", nil, false],
  ["[Limpieza] Leche de avena — lote 3", nil, false],
  ["[Panadería] Leche de coco — lote 3", nil, false],
  ["[Lácteos] Agua mineral con gas — lote 3", nil, false],
  ["[Verdulería] Agua mineral sin gas — lote 3", nil, true],
  ["[Carnicería] Jugo de naranja — lote 3", nil, false],
  ["[Bebidas] Gaseosa cola — lote 3", nil, false],
  ["[Limpieza] Gaseosa lima limón — lote 3", nil, false],
  ["[Panadería] Agua tónica — lote 3", nil, false],
  ["[Lácteos] Cerveza artesanal — lote 3", nil, false],
  ["[Verdulería] Vino tinto Malbec — lote 3", nil, false],
  ["[Carnicería] Vino blanco Chardonnay — lote 3", nil, true],
  ["[Bebidas] Papel de aluminio — lote 3", nil, false],
  ["[Limpieza] Film plástico — lote 3", nil, false],
  ["[Panadería] Bolsas de residuos grandes — lote 3", nil, false],
  ["[Lácteos] Bolsas de residuos chicas — lote 3", nil, false],
  ["[Verdulería] Papel de cocina — lote 3", nil, false],
  ["[Carnicería] Papel higiénico — lote 3", nil, false],
  ["[Bebidas] Detergente — lote 3", nil, true],
  ["[Limpieza] Esponjas de cocina — lote 3", nil, false],
  ["[Panadería] Lavandina — lote 3", nil, false],
  ["[Lácteos] Desengrasante — lote 3", nil, false],
  ["[Verdulería] Shampoo — lote 3", nil, false],
  ["[Carnicería] Acondicionador — lote 3", nil, false],
  ["[Bebidas] Jabón de tocador — lote 3", nil, false],
  ["[Limpieza] Pasta dental — lote 3", nil, true],
  ["[Panadería] Hilo dental — lote 3", nil, false],
  ["[Lácteos] Leche entera (1L) — lote 4", nil, false],
  ["[Verdulería] Leche descremada (1L) — lote 4", nil, false],
  ["[Carnicería] Yogur natural — lote 4", nil, false],
  ["[Bebidas] Yogur griego — lote 4", nil, false],
  ["[Limpieza] Queso mozzarella — lote 4", nil, false],
  ["[Panadería] Queso cheddar — lote 4", nil, true],
  ["[Lácteos] Queso brie — lote 4", nil, false],
  ["[Verdulería] Queso parmesano — lote 4", nil, false],
].each { |t, d, c| inventario_completo_d.todo_list_items.create!(title: t, description: d, completed: c) }

puts "Seeded #{TodoList.count} lists with #{TodoListItem.count} items."
